### ISSUE TITLE
Mouse-over help on certain UI elements

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-scope-feedback#22]
Some of the buttons would benefit from those little annotations that pop up when you pause the mouse over the element.  Particularly, the little symbols (target, writing thing, refresh).

**Comment by ennerf** [comment]
Partially fixed in snapshot. Unlabeled buttons now have a tooltip

![image](https://user-images.githubusercontent.com/5491587/48277474-1624f100-e44b-11e8-9db6-25a623e89f98.png)

**Comment by daverolli** [comment]
I like these a lot.  Maybe make the descriptions a little more clear.  

For the Plot Freq / Command Sliders I would suggest:
* Set specific --> Set Specific Value or (this is closer to what dialog box that pops up is titles)

For the Position / Effort Reference Points
* Set current --> Get Current Value

**Comment by ennerf** [comment]
How about `Set Specific Value...` and `Get Feedback Value` (or `Copy Feedback Value`) ? 'current' is already a bit of an overloaded term

**Comment by ennerf** [comment]
Fixed, but #77 adds more.
