### ISSUE TITLE
On Dashboard, make some elements faded if module is offline

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-scope-feedback#26]
The 'stale' status is good, but maybe greying the word stale and states in the 'Status' box would make it more clear at a glance that you've shifted over to a module that isn't active.

**Comment by ennerf** [comment]
![image](https://user-images.githubusercontent.com/5491587/48277382-d0682880-e44a-11e8-9623-39aa038f7019.png)

Now all leds are grey and the box around it is disabled

**Comment by daverolli** [comment]
Works as described on macOS and Windows.  I'm not sure I understood what you mean by "too difficult to see if modules were on the network".  I like having the info still be readable on the Dashboard Tab like you have now.  Might be good if the action buttons on the Dashboard are disables, like the options are when you right-click.  

Having the Monitoring / Gains Tabs still be active seems a little weird to me.  I thought old behavior where those tabs were disabled made more sense.

**Comment by ennerf** [comment]
My initial "fix" greyed out everything in the GUI even if there is no selection. That made it really difficult to read through the UI if e.g. someone would take a look at Scope before having modules.

As mentioned on Slack, parts of the monitoring tab (e.g. frequency slider and close-all button) can still be used even if the currently focused module is stale. Gains etc. can also still be saved. Not sure if that's a big use case though.
