### ISSUE TITLE
Highlighting Obscures Name in Main Panel

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-scope-feedback#27]
When you highlight the text, the background highlight pretty much obscures the text.  The 'Family' name  font color inverts to white, which would probably be a good thing to do for 'Name'.

**Comment by ennerf** [comment]
was able to reproduce it on Windows. This happens if you're in the Family name field and then press tab. When you use the mouse it works correctly (at least on Windows). Will look into it

**Comment by ennerf** [comment]
lost the ability to reproduce. not sure what I did

**Comment by ennerf** [comment]
Likely fixed. @daverolli please confirm

**Comment by daverolli** [comment]
Same issue as before in macOS.  I also can't reproduce in Windows.

**Comment by ennerf** [comment]
Still seems to be an issue

**Comment by ennerf** [comment]
not an issue anymore in the new design
