### ISSUE TITLE
Dashboard: add graphics

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/hebi-scope-feedback#8]
currently the dashboard graphic is hardcoded to be an X5 wire-frame. We should add X8, the IO-Board, and maybe phone renderings

**Comment by daverolli** [comment]
Very cool.  It'd be cool to have at least a generic image for a mobile device.  Some flat thing with a touch-screen.  Crazy would be having an image of the actual device, or at least different ones for phones / tablets.

**Comment by daverolli** [comment]
I'll see if I can get a wireframe of a phone that looks similar to the angle / view of the modules.

**Comment by ennerf** [comment]
Jan added a graphic for phones
